# Generated by Django 4.1.5 on 2023-04-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=50)),
                ('ethnicity', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('lga', models.CharField(max_length=50)),
                ('place_of_pry_ass', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('garrison', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('platoon', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
