# Generated by Django 4.1.5 on 2023-05-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_consoleuser_first_name_consoleuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consoleuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='consoleuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
