# Generated by Django 4.1.5 on 2023-05-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_consoleuser_email_alter_consoleuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='consoleuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='consoleuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consoleuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
