# Generated by Django 4.1.5 on 2023-05-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientengagement',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
