# Generated by Django 4.1.5 on 2023-05-13 13:24

from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('group_type', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=5)),
                ('genotype', models.CharField(max_length=5)),
                ('age', models.CharField(max_length=3, validators=[patient.models.validate_age])),
                ('sex', models.CharField(max_length=10)),
                ('social_handle', models.CharField(blank=True, max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('garrison', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('platoon', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('place_of_pry_assignment', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
